-- Remove MysISAM Indexes

alter table clientaddons drop index `index`;

-- convert to InnoDB

alter table ai_agents type=InnoDB;
alter table ai_threattospellid type=InnoDB;
alter table areatriggers type=InnoDB;
alter table auctionhouse type=InnoDB;
alter table banned_names type=InnoDB;
alter table banned_phrases type=InnoDB;
alter table clientaddons type=InnoDB;
alter table command_overrides type=InnoDB;
alter table creature_formations type=InnoDB;
alter table creature_names type=InnoDB;
alter table creature_names_localized type=InnoDB;
alter table creature_proto type=InnoDB;
alter table creature_quest_finisher type=InnoDB;
alter table creature_quest_starter type=InnoDB;
alter table creature_spawns type=InnoDB;
alter table creature_staticspawns type=InnoDB;
alter table creature_waypoints type=InnoDB;
alter table creatureloot type=InnoDB;
alter table fishing type=InnoDB;
alter table fishingloot type=InnoDB;
alter table gameobject_names type=InnoDB;
alter table gameobject_names_localized type=InnoDB;
alter table gameobject_quest_finisher type=InnoDB;
alter table gameobject_quest_item_binding type=InnoDB;
alter table gameobject_quest_pickup_binding type=InnoDB;
alter table gameobject_quest_starter type=InnoDB;
alter table gameobject_spawns type=InnoDB;
alter table gameobject_staticspawns type=InnoDB;
alter table graveyards type=InnoDB;
alter table item_randomprop_groups type=InnoDB;
alter table item_randomsuffix_groups type=InnoDB;
alter table itemloot type=InnoDB;
alter table itempages type=InnoDB;
alter table itempages_localized type=InnoDB;
alter table itempetfood type=InnoDB;
alter table items type=InnoDB;
alter table items_localized type=InnoDB;
alter table map_checkpoint type=InnoDB;
alter table npc_gossip_textid type=InnoDB;
alter table npc_monstersay type=InnoDB;
alter table npc_text type=InnoDB;
alter table npc_text_localized type=InnoDB;
alter table objectloot type=InnoDB;
alter table petdefaultspells type=InnoDB;
alter table pickpocketingloot type=InnoDB;
alter table playercreateinfo type=InnoDB;
alter table playercreateinfo_bars type=InnoDB;
alter table playercreateinfo_items type=InnoDB;
alter table playercreateinfo_skills type=InnoDB;
alter table playercreateinfo_spells type=InnoDB;
alter table prospectingloot type=InnoDB;
alter table quests type=InnoDB;
alter table quests_localized type=InnoDB;
alter table recall type=InnoDB;
alter table reputation_creature_onkill type=InnoDB;
alter table reputation_faction_onkill type=InnoDB;
alter table reputation_instance_onkill type=InnoDB;
alter table skinningloot type=InnoDB;
alter table spell_disable type=InnoDB;
alter table spell_disable_trainers type=InnoDB;
alter table spell_proc_data type=InnoDB;
alter table spellextra type=InnoDB;
alter table spells112 type=InnoDB;
alter table teleport_coords type=InnoDB;
alter table totemspells type=InnoDB;
alter table trainer_defs type=InnoDB;
alter table trainer_spells type=InnoDB;
alter table trainerspelloverride type=InnoDB;
alter table transport_creatures type=InnoDB;
alter table transport_data type=InnoDB;
alter table vendors type=InnoDB;
alter table weather type=InnoDB;
alter table wordfilter_character_names type=InnoDB;
alter table wordfilter_chat type=InnoDB;
alter table worldmap_info type=InnoDB;
alter table zoneguards type=InnoDB;

-- Add InnoDB Indices

ALTER TABLE `ai_agents` ADD UNIQUE `a`(`entry`, `spell`, `type`);
ALTER TABLE `ai_threattospellid` ADD UNIQUE `a`(`spell`);
ALTER TABLE `areatriggers` ADD UNIQUE `a`(`entry`);
ALTER TABLE `auctionhouse` ADD UNIQUE `a`(`id`);
alter table `auctionhouse` drop index entryid;
ALTER TABLE `auctionhouse` ADD PRIMARY KEY (`id`);
ALTER TABLE `banned_names` ADD UNIQUE `a`(`name`);
ALTER TABLE `banned_phrases` ADD UNIQUE `a`(`phrase`);
ALTER TABLE `clientaddons` ADD UNIQUE `a`(`id`);
ALTER TABLE `command_overrides` ADD UNIQUE `a`(`command_name`);
ALTER TABLE `creature_formations` ADD UNIQUE `a`(`spawn_id`);
ALTER TABLE `creature_names` ADD UNIQUE `a`(`entry`);
alter table `creature_names` drop index entry;
ALTER TABLE `creature_names` ADD PRIMARY KEY (`entry`);
