CREATE TABLE `ai_agents` (
  `entryId` int unsigned NOT NULL default '0',
  `AI_AGENT` smallint unsigned NOT NULL default '0',
  `procEvent` int unsigned NOT NULL default '0',
  `procChance` int unsigned NOT NULL default '0',
  `procCount` int unsigned NOT NULL default '0',
  `spellId` int unsigned NOT NULL default '0',
  `spellType` int unsigned NOT NULL default '0',
  `spelltargetType` int unsigned NOT NULL default '0',
  `spellCooldown` int NOT NULL default '0',
  `floatMisc1` float NOT NULL default '0',
  `Misc2` int unsigned NOT NULL default '0',
  PRIMARY KEY  (`entryId`,`AI_AGENT`,`spellId`)
);
CREATE TABLE `ai_threattospellid` (
  `spellId` int unsigned NOT NULL default '0',
  `mod` int NOT NULL default '0',
  PRIMARY KEY  (`spellId`)
);
CREATE TABLE `areatriggers` (
  `AreaTriggerid` int unsigned NOT NULL default '0',
  `Type` tinyint unsigned default '0',
  `Mapid` int unsigned default NULL,
  `Screen` int unsigned default NULL,
  `Name` varchar(100) default '0',
  `x` float NOT NULL default '0',
  `y` float NOT NULL default '0',
  `z` float NOT NULL default '0',
  `o` float NOT NULL default '0',
  `required_honor_rank` int unsigned NOT NULL default '0',
  `required_level` tinyint unsigned NOT NULL default '0',
  PRIMARY KEY  (`AreaTriggerid`)
);
CREATE TABLE `auctionhouse` (
  `entryid` int NOT NULL auto_increment,
  `auctioneer` bigint unsigned NOT NULL default '0',
  `AHid` int NOT NULL default '0',
  UNIQUE KEY `entryid` (`entryid`)
);
CREATE TABLE `banned_names` (
  `name` varchar(30) NOT NULL
);
CREATE TABLE `banned_phrases` (
  `phrase` varchar(250) NOT NULL,
  PRIMARY KEY  (`phrase`)
);
CREATE TABLE `clientaddons` (
  `id` int unsigned NOT NULL auto_increment,
  `name` varchar(50) default NULL,
  `crc` bigint unsigned default NULL,
  `banned` int unsigned NOT NULL default '0',
  `showinlist` int unsigned NOT NULL default '0',
  PRIMARY KEY  (`id`),
  KEY `index` (`name`)
);
CREATE TABLE `command_overrides` (
  `command_name` varchar(100) NOT NULL,
  `access_level` varchar(10) NOT NULL,
  PRIMARY KEY  (`command_name`)
);
CREATE TABLE `creature_formations` (
  `creature_sqlid` int unsigned NOT NULL default '0',
  `followtarget_sqlid` int unsigned NOT NULL default '0',
  `follow_angle` float NOT NULL default '0',
  `follow_dist` float NOT NULL default '0',
  PRIMARY KEY  (`creature_sqlid`)
);
CREATE TABLE `creature_names` (
  `entry` int unsigned NOT NULL default '0',
  `creature_name` varchar(100) NOT NULL,
  `Subname` varchar(100) NOT NULL,
  `Flags1` int unsigned default '0',
  `type` int unsigned default '0',
  `Family` int unsigned default '0',
  `Rank` int unsigned default '0',
  `unk4` int unsigned default '0',
  `SpellDataID` int unsigned default NULL,
  `male_displayid` int NOT NULL,
  `female_displayid` int NOT NULL,
  `unknown_int1` int NOT NULL default '0',
  `unknown_int2` int NOT NULL default '0',
  `unknown_float1` float NOT NULL default '1',
  `unknown_float2` float NOT NULL default '1',
  `Civilian` int unsigned default NULL,
  `Leader` tinyint unsigned default NULL,
  UNIQUE KEY `entry` (`entry`)
);
CREATE TABLE `creature_proto` (
  `entry` int unsigned NOT NULL default '0',
  `minlevel` int unsigned NOT NULL,
  `maxlevel` int unsigned NOT NULL,
  `faction` int unsigned NOT NULL default '0',
  `minhealth` int unsigned NOT NULL,
  `maxhealth` int unsigned NOT NULL,
  `mana` int unsigned NOT NULL default '0',
  `scale` float NOT NULL default '0',
  `npcflags` int unsigned NOT NULL default '0',
  `attacktime` int unsigned NOT NULL default '0',
  `mindamage` float NOT NULL default '0',
  `maxdamage` float NOT NULL default '0',
  `rangedattacktime` int unsigned NOT NULL default '0',
  `rangedmindamage` float unsigned NOT NULL default '0',
  `rangedmaxdamage` float unsigned NOT NULL default '0',
  `mountdisplayid` int unsigned NOT NULL default '0',
  `item1slotdisplay` int unsigned NOT NULL default '0',
  `item1info1` int unsigned NOT NULL default '0',
  `item1info2` int unsigned NOT NULL default '0',
  `item2slotdisplay` int unsigned NOT NULL default '0',
  `item2info1` int unsigned NOT NULL default '0',
  `item2info2` int unsigned NOT NULL default '0',
  `item3slotdisplay` int unsigned NOT NULL default '0',
  `item3info1` int unsigned NOT NULL default '0',
  `item3info2` int unsigned NOT NULL default '0',
  `respawntime` int unsigned NOT NULL default '0',
  `resistance0_armor` int unsigned NOT NULL default '0',
  `resistance1` int unsigned NOT NULL default '0',
  `resistance2` int unsigned NOT NULL default '0',
  `resistance3` int unsigned NOT NULL default '0',
  `resistance4` int unsigned NOT NULL default '0',
  `resistance5` int unsigned NOT NULL default '0',
  `resistance6` int unsigned NOT NULL default '0',
  `combat_reach` float NOT NULL default '0',
  `bounding_radius` float NOT NULL default '0',
  `auras` longtext NOT NULL,
  `boss` int unsigned NOT NULL default '0',
  `money` int NOT NULL default '0',
  `invisibility_type` int unsigned NOT NULL,
  `death_state` int unsigned NOT NULL,
  `walk_speed` float NOT NULL default '2.5',
  `run_speed` float NOT NULL default '8',
  `fly_speed` float NOT NULL default '14',
  `extra_a9_flags` int NOT NULL default '0',
  PRIMARY KEY  (`entry`),
  UNIQUE KEY `ID` (`entry`)
);
CREATE TABLE `creature_quest_finisher` (
  `id` int unsigned NOT NULL default '0',
  `quest` int unsigned NOT NULL default '0',
  PRIMARY KEY  (`id`,`quest`)
);
CREATE TABLE `creature_quest_starter` (
  `id` int unsigned NOT NULL default '0',
  `quest` int unsigned NOT NULL default '0',
  PRIMARY KEY  (`id`,`quest`)
);
CREATE TABLE `creature_spawns` (
  `id` int unsigned NOT NULL auto_increment,
  `entry` int NOT NULL,
  `Map` int NOT NULL,
  `x` float NOT NULL,
  `y` float NOT NULL,
  `z` float NOT NULL,
  `o` float NOT NULL,
  `movetype` int NOT NULL default '0',
  `displayid` int unsigned NOT NULL default '0',
  `factionid` int NOT NULL default '14',
  `flags` int NOT NULL default '0',
  `bytes` int NOT NULL default '0',
  `bytes2` int NOT NULL default '0',
  `emote_state` int NOT NULL default '0',
  `npc_respawn_link` int NOT NULL default '0',
  `channel_spell` int NOT NULL default '0',
  `channel_target_sqlid` int NOT NULL default '0',
  `channel_target_sqlid_creature` int NOT NULL default '0',
  PRIMARY KEY  (`id`)
);
CREATE TABLE `creature_staticspawns` (
  `id` int unsigned NOT NULL auto_increment,
  `entry` int NOT NULL,
  `Map` int NOT NULL,
  `x` float NOT NULL,
  `y` float NOT NULL,
  `z` float NOT NULL,
  `o` float NOT NULL,
  `movetype` int NOT NULL default '0',
  `displayid` int unsigned NOT NULL default '0',
  `factionid` int NOT NULL default '35',
  `flags` int NOT NULL default '0',
  `bytes` int NOT NULL default '0',
  `bytes2` int NOT NULL default '0',
  `emote_state` int NOT NULL default '0',
  `npc_respawn_link` int NOT NULL default '0',
  PRIMARY KEY  (`id`),
  UNIQUE KEY `id` (`id`)
);
CREATE TABLE `creature_waypoints` (
  `creatureid` int unsigned NOT NULL default '0',
  `waypointid` int unsigned NOT NULL default '0',
  `x` float NOT NULL default '0',
  `y` float NOT NULL default '0',
  `z` float NOT NULL default '0',
  `waittime` int unsigned NOT NULL default '0',
  `flags` int unsigned NOT NULL default '0',
  `forwardemoteoneshot` tinyint unsigned NOT NULL default '0',
  `forwardemoteid` int unsigned NOT NULL default '0',
  `backwardemoteoneshot` tinyint unsigned NOT NULL default '0',
  `backwardemoteid` int unsigned NOT NULL default '0',
  `forwardskinid` int unsigned NOT NULL default '0',
  `backwardskinid` int unsigned NOT NULL default '0',
  PRIMARY KEY  (`creatureid`,`waypointid`)
);
CREATE TABLE `creatureloot` (
  `index` int unsigned NOT NULL auto_increment,
  `entryid` int NOT NULL default '0',
  `itemid` int NOT NULL default '0',
  `percentchance` float NOT NULL default '0',
  `heroicpercentchance` float NOT NULL default '0',
  `mincount` int NOT NULL default '1',
  `maxcount` int NOT NULL default '1',
  PRIMARY KEY  (`entryid`,`itemid`,`percentchance`,`heroicpercentchance`,`mincount`,`maxcount`),
  UNIQUE KEY `index` (`index`)
);
CREATE TABLE `fishing` (
  `Zone` int unsigned NOT NULL default '0',
  `MinSkill` int unsigned default NULL,
  `MaxSkill` int unsigned default NULL,
  UNIQUE KEY `Zone` (`Zone`)
);
CREATE TABLE `fishingloot` (
  `index` int unsigned NOT NULL auto_increment,
  `entryid` int unsigned NOT NULL default '0',
  `itemid` int unsigned NOT NULL default '0',
  `percentchance` float NOT NULL default '0',
  `heroicpercentchance` float NOT NULL default '0',
  `mincount` int unsigned NOT NULL default '1',
  `maxcount` int unsigned NOT NULL default '1',
  PRIMARY KEY  (`index`),
  UNIQUE KEY `index` (`index`)
);
CREATE TABLE `gameobject_names` (
  `entry` int unsigned NOT NULL default '0',
  `Type` int unsigned NOT NULL default '0',
  `DisplayID` int unsigned NOT NULL default '0',
  `Name` varchar(100) NOT NULL,
  `spellfocus` int unsigned NOT NULL default '0',
  `sound1` int unsigned NOT NULL default '0',
  `sound2` int unsigned NOT NULL default '0',
  `sound3` int unsigned NOT NULL default '0',
  `sound4` int unsigned NOT NULL default '0',
  `sound5` int unsigned NOT NULL default '0',
  `sound6` int unsigned NOT NULL default '0',
  `sound7` int unsigned NOT NULL default '0',
  `sound8` int unsigned NOT NULL default '0',
  `sound9` int unsigned NOT NULL default '0',
  `unknown1` int unsigned NOT NULL default '0',
  `unknown2` int unsigned NOT NULL default '0',
  `unknown3` int unsigned NOT NULL default '0',
  `unknown4` int unsigned NOT NULL default '0',
  `unknown5` int unsigned NOT NULL default '0',
  `unknown6` int unsigned NOT NULL default '0',
  `unknown7` int unsigned NOT NULL default '0',
  `unknown8` int unsigned NOT NULL default '0',
  `unknown9` int unsigned NOT NULL default '0',
  `unknown10` int unsigned NOT NULL default '0',
  `unknown11` int unsigned NOT NULL default '0',
  `unknown12` int unsigned NOT NULL default '0',
  `unknown13` int unsigned NOT NULL default '0',
  `unknown14` int unsigned NOT NULL default '0',
  UNIQUE KEY `entry` (`entry`)
);
CREATE TABLE `gameobject_quest_finisher` (
  `id` int unsigned NOT NULL default '0',
  `quest` int unsigned NOT NULL default '0',
  PRIMARY KEY  (`id`,`quest`)
);
CREATE TABLE `gameobject_quest_item_binding` (
  `gameobject_entry` int NOT NULL default '0',
  `quest_id` int NOT NULL default '0',
  `item_id` int NOT NULL default '0',
  `item_count` int NOT NULL default '0'
);
CREATE TABLE `gameobject_quest_pickup_binding` (
  `gameobject_entry` int NOT NULL default '0',
  `quest_id` int NOT NULL default '0',
  `required_count` int NOT NULL default '0'
);
CREATE TABLE `gameobject_quest_starter` (
  `id` int unsigned NOT NULL default '0',
  `quest` int unsigned NOT NULL default '0',
  PRIMARY KEY  (`id`,`quest`)
);
CREATE TABLE `gameobject_spawns` (
  `id` int unsigned NOT NULL auto_increment,
  `Entry` int unsigned NOT NULL default '0',
  `Map` int unsigned NOT NULL default '0',
  `x` float NOT NULL default '0',
  `y` float NOT NULL default '0',
  `z` float NOT NULL default '0',
  `Facing` float NOT NULL default '0',
  `o1` float NOT NULL default '0',
  `o2` float NOT NULL default '0',
  `o3` float NOT NULL default '0',
  `o4` float NOT NULL default '0',
  `State` int unsigned NOT NULL default '0',
  `Flags` int unsigned NOT NULL default '0',
  `Faction` int unsigned NOT NULL default '0',
  `Scale` float NOT NULL default '0',
  `stateNpcLink` int unsigned NOT NULL default '0',
  PRIMARY KEY  (`id`),
  KEY `Map` (`Map`)
);
CREATE TABLE `gameobject_staticspawns` (
  `id` int NOT NULL auto_increment,
  `entry` int NOT NULL,
  `map` int NOT NULL default '0',
  `x` float NOT NULL,
  `y` float NOT NULL,
  `z` float NOT NULL,
  `facing` float NOT NULL,
  `o` float NOT NULL,
  `o1` float NOT NULL,
  `o2` float NOT NULL,
  `o3` float NOT NULL,
  `state` int NOT NULL default '0',
  `flags` int NOT NULL default '0',
  `faction` int NOT NULL default '0',
  `scale` float NOT NULL,
  `respawnNpcLink` int NOT NULL default '0',
  PRIMARY KEY  (`id`)
);
CREATE TABLE `graveyards` (
  `id` int unsigned NOT NULL auto_increment,
  `x` float NOT NULL default '0',
  `y` float NOT NULL default '0',
  `z` float NOT NULL default '0',
  `o` float NOT NULL default '0',
  `zoneid` int unsigned NOT NULL default '0',
  `adjacentzoneid` int unsigned NOT NULL default '0',
  `mapid` int unsigned NOT NULL default '0',
  `factionid` int unsigned NOT NULL default '0',
  `name` varchar(255) NOT NULL,
  PRIMARY KEY  (`id`),
  UNIQUE KEY `index` (`id`)
);
CREATE TABLE `item_randomprop_groups` (
  `entry_id` int NOT NULL,
  `randomprops_entryid` int NOT NULL,
  `chance` float NOT NULL,
  PRIMARY KEY  (`entry_id`,`randomprops_entryid`)
);
CREATE TABLE `item_randomsuffix_groups` (
  `entry_id` int NOT NULL,
  `randomsuffix_entryid` int NOT NULL,
  `chance` float NOT NULL,
  PRIMARY KEY  (`entry_id`,`randomsuffix_entryid`)
);
CREATE TABLE `itemloot` (
  `index` int unsigned NOT NULL auto_increment,
  `entryid` int unsigned NOT NULL default '0',
  `itemid` int unsigned NOT NULL default '25',
  `percentchance` float NOT NULL default '0',
  `heroicpercentchance` float NOT NULL default '0',
  `mincount` int unsigned NOT NULL default '1',
  `maxcount` int unsigned NOT NULL default '1',
  PRIMARY KEY  (`index`),
  UNIQUE KEY `index` (`index`),
  KEY `i_gameobj_loot_entry` (`entryid`)
);
CREATE TABLE `itempages` (
  `entry` int unsigned NOT NULL default '0',
  `text` longtext NOT NULL,
  `next_page` int unsigned NOT NULL default '0',
  UNIQUE KEY `entry` (`entry`)
);
CREATE TABLE `items` (
  `entry` int unsigned NOT NULL default '0',
  `class` int NOT NULL default '0',
  `subclass` int NOT NULL default '0',
  `field4` int NOT NULL default '-1',
  `name1` varchar(255) NOT NULL,
  `name2` varchar(255) NOT NULL default '',
  `name3` varchar(255) NOT NULL default '',
  `name4` varchar(255) NOT NULL default '',
  `displayid` int unsigned NOT NULL default '0',
  `quality` int NOT NULL default '0',
  `flags` int NOT NULL default '0',
  `buyprice` int NOT NULL default '0',
  `sellprice` int NOT NULL default '0',
  `inventorytype` int NOT NULL default '0',
  `allowableclass` int NOT NULL default '0',
  `allowablerace` int NOT NULL default '0',
  `itemlevel` int NOT NULL default '0',
  `requiredlevel` int NOT NULL default '0',
  `RequiredSkill` int NOT NULL default '0',
  `RequiredSkillRank` int NOT NULL default '0',
  `RequiredSkillSubRank` int NOT NULL default '0',
  `RequiredPlayerRank1` int NOT NULL default '0',
  `RequiredPlayerRank2` int NOT NULL default '0',
  `RequiredFaction` int NOT NULL default '0',
  `RequiredFactionStanding` int NOT NULL default '0',
  `Unique` int NOT NULL default '0',
  `maxcount` int NOT NULL default '0',
  `ContainerSlots` int NOT NULL default '0',
  `stat_type1` int NOT NULL default '0',
  `stat_value1` int NOT NULL default '0',
  `stat_type2` int NOT NULL default '0',
  `stat_value2` int NOT NULL default '0',
  `stat_type3` int NOT NULL default '0',
  `stat_value3` int NOT NULL default '0',
  `stat_type4` int NOT NULL default '0',
  `stat_value4` int NOT NULL default '0',
  `stat_type5` int NOT NULL default '0',
  `stat_value5` int NOT NULL default '0',
  `stat_type6` int NOT NULL default '0',
  `stat_value6` int NOT NULL default '0',
  `stat_type7` int NOT NULL default '0',
  `stat_value7` int NOT NULL default '0',
  `stat_type8` int NOT NULL default '0',
  `stat_value8` int NOT NULL default '0',
  `stat_type9` int NOT NULL default '0',
  `stat_value9` int NOT NULL default '0',
  `stat_type10` int NOT NULL default '0',
  `stat_value10` int NOT NULL default '0',
  `dmg_min1` float NOT NULL default '0',
  `dmg_max1` float NOT NULL default '0',
  `dmg_type1` int NOT NULL default '0',
  `dmg_min2` float NOT NULL default '0',
  `dmg_max2` float NOT NULL default '0',
  `dmg_type2` int NOT NULL default '0',
  `dmg_min3` float NOT NULL default '0',
  `dmg_max3` float NOT NULL default '0',
  `dmg_type3` int NOT NULL default '0',
  `dmg_min4` float NOT NULL default '0',
  `dmg_max4` float NOT NULL default '0',
  `dmg_type4` int NOT NULL default '0',
  `dmg_min5` float NOT NULL default '0',
  `dmg_max5` float NOT NULL default '0',
  `dmg_type5` int NOT NULL default '0',
  `armor` int NOT NULL default '0',
  `holy_res` int NOT NULL default '0',
  `fire_res` int NOT NULL default '0',
  `nature_res` int NOT NULL default '0',
  `frost_res` int NOT NULL default '0',
  `shadow_res` int NOT NULL default '0',
  `arcane_res` int NOT NULL default '0',
  `delay` int NOT NULL default '0',
  `ammo_type` int NOT NULL default '0',
  `range` float NOT NULL default '0',
  `spellid_1` int NOT NULL default '0',
  `spelltrigger_1` int NOT NULL default '0',
  `spellcharges_1` int NOT NULL default '0',
  `spellcooldown_1` int NOT NULL default '0',
  `spellcategory_1` int NOT NULL default '0',
  `spellcategorycooldown_1` int NOT NULL default '0',
  `spellid_2` int NOT NULL default '0',
  `spelltrigger_2` int NOT NULL default '0',
  `spellcharges_2` int NOT NULL default '0',
  `spellcooldown_2` int NOT NULL default '0',
  `spellcategory_2` int NOT NULL default '0',
  `spellcategorycooldown_2` int NOT NULL default '0',
  `spellid_3` int NOT NULL default '0',
  `spelltrigger_3` int NOT NULL default '0',
  `spellcharges_3` int NOT NULL default '0',
  `spellcooldown_3` int NOT NULL default '0',
  `spellcategory_3` int NOT NULL default '0',
  `spellcategorycooldown_3` int NOT NULL default '0',
  `spellid_4` int NOT NULL default '0',
  `spelltrigger_4` int NOT NULL default '0',
  `spellcharges_4` int NOT NULL default '0',
  `spellcooldown_4` int NOT NULL default '0',
  `spellcategory_4` int NOT NULL default '0',
  `spellcategorycooldown_4` int NOT NULL default '0',
  `spellid_5` int NOT NULL default '0',
  `spelltrigger_5` int NOT NULL default '0',
  `spellcharges_5` int NOT NULL default '0',
  `spellcooldown_5` int NOT NULL default '0',
  `spellcategory_5` int NOT NULL default '0',
  `spellcategorycooldown_5` int NOT NULL default '0',
  `bonding` int NOT NULL default '0',
  `description` varchar(255) NOT NULL default '',
  `page_id` int NOT NULL default '0',
  `page_language` int NOT NULL default '0',
  `page_material` int NOT NULL default '0',
  `quest_id` int NOT NULL default '0',
  `lock_id` int NOT NULL default '0',
  `lock_material` int NOT NULL default '0',
  `sheathID` int NOT NULL default '0',
  `randomprop` int NOT NULL default '0',
  `unk203_1` int NOT NULL default '0',
  `block` int NOT NULL default '0',
  `itemset` int NOT NULL default '0',
  `MaxDurability` int NOT NULL default '0',
  `ZoneNameID` int NOT NULL default '0',
  `mapid` int default NULL,
  `bagfamily` int NOT NULL default '0',
  `TotemCategory` int default NULL,
  `socket_color_1` int default NULL,
  `unk201_3` int NOT NULL default '0',
  `socket_color_2` int default NULL,
  `unk201_5` int NOT NULL default '0',
  `socket_color_3` int default NULL,
  `unk201_7` int NOT NULL default '0',
  `socket_bonus` int default NULL,
  `GemProperties` int default NULL,
  `ItemExtendedCost` int default NULL,
  `ReqDisenchantSkill` int NOT NULL default '-1',
  `unk2` int NOT NULL default '0',
  PRIMARY KEY  (`entry`),
  UNIQUE KEY `entry` (`entry`)
);
CREATE TABLE `npc_gossip_textid` (
  `entryid` int unsigned NOT NULL default '0',
  `textid` int unsigned NOT NULL default '0',
  PRIMARY KEY  (`entryid`),
  UNIQUE KEY `index` (`entryid`)
);
CREATE TABLE `npc_monstersay` (
  `entry` int unsigned NOT NULL default '0',
  `event` int unsigned NOT NULL default '0',
  `chance` float NOT NULL default '0',
  `language` int unsigned NOT NULL default '0',
  `type` int unsigned NOT NULL default '0',
  `monstername` longtext,
  `text0` longtext,
  `text1` longtext,
  `text2` longtext,
  `text3` longtext,
  `text4` longtext
);
CREATE TABLE `npc_text` (
  `entry` int unsigned NOT NULL default '0',
  `prob0` float NOT NULL default '0',
  `text0_0` longtext NOT NULL,
  `text0_1` longtext NOT NULL,
  `lang0` int unsigned NOT NULL default '0',
  `em0_0` int unsigned NOT NULL default '0',
  `em0_1` int unsigned NOT NULL default '0',
  `em0_2` int unsigned NOT NULL default '0',
  `em0_3` int unsigned NOT NULL default '0',
  `em0_4` int unsigned NOT NULL default '0',
  `em0_5` int unsigned NOT NULL default '0',
  `prob1` float NOT NULL default '0',
  `text1_0` longtext NOT NULL,
  `text1_1` longtext NOT NULL,
  `lang1` int unsigned NOT NULL default '0',
  `em1_0` int unsigned NOT NULL default '0',
  `em1_1` int unsigned NOT NULL default '0',
  `em1_2` int unsigned NOT NULL default '0',
  `em1_3` int unsigned NOT NULL default '0',
  `em1_4` int unsigned NOT NULL default '0',
  `em1_5` int unsigned NOT NULL default '0',
  `prob2` float NOT NULL default '0',
  `text2_0` longtext NOT NULL,
  `text2_1` longtext NOT NULL,
  `lang2` int unsigned NOT NULL default '0',
  `em2_0` int unsigned NOT NULL default '0',
  `em2_1` int unsigned NOT NULL default '0',
  `em2_2` int unsigned NOT NULL default '0',
  `em2_3` int unsigned NOT NULL default '0',
  `em2_4` int unsigned NOT NULL default '0',
  `em2_5` int unsigned NOT NULL default '0',
  `prob3` float NOT NULL default '0',
  `text3_0` longtext NOT NULL,
  `text3_1` longtext NOT NULL,
  `lang3` int unsigned NOT NULL default '0',
  `em3_0` int unsigned NOT NULL default '0',
  `em3_1` int unsigned NOT NULL default '0',
  `em3_2` int unsigned NOT NULL default '0',
  `em3_3` int unsigned NOT NULL default '0',
  `em3_4` int unsigned NOT NULL default '0',
  `em3_5` int unsigned NOT NULL default '0',
  `prob4` float NOT NULL default '0',
  `text4_0` longtext NOT NULL,
  `text4_1` longtext NOT NULL,
  `lang4` int unsigned NOT NULL default '0',
  `em4_0` int unsigned NOT NULL default '0',
  `em4_1` int unsigned NOT NULL default '0',
  `em4_2` int unsigned NOT NULL default '0',
  `em4_3` int unsigned NOT NULL default '0',
  `em4_4` int unsigned NOT NULL default '0',
  `em4_5` int unsigned NOT NULL default '0',
  `prob5` float NOT NULL default '0',
  `text5_0` longtext NOT NULL,
  `text5_1` longtext NOT NULL,
  `lang5` int unsigned NOT NULL default '0',
  `em5_0` int unsigned NOT NULL default '0',
  `em5_1` int unsigned NOT NULL default '0',
  `em5_2` int unsigned NOT NULL default '0',
  `em5_3` int unsigned NOT NULL default '0',
  `em5_4` int unsigned NOT NULL default '0',
  `em5_5` int unsigned NOT NULL default '0',
  `prob6` float NOT NULL default '0',
  `text6_0` longtext NOT NULL,
  `text6_1` longtext NOT NULL,
  `lang6` int unsigned NOT NULL default '0',
  `em6_0` int unsigned NOT NULL default '0',
  `em6_1` int unsigned NOT NULL default '0',
  `em6_2` int unsigned NOT NULL default '0',
  `em6_3` int unsigned NOT NULL default '0',
  `em6_4` int unsigned NOT NULL default '0',
  `em6_5` int unsigned NOT NULL default '0',
  `prob7` float NOT NULL default '0',
  `text7_0` longtext NOT NULL,
  `text7_1` longtext NOT NULL,
  `lang7` int unsigned NOT NULL default '0',
  `em7_0` int unsigned NOT NULL default '0',
  `em7_1` int unsigned NOT NULL default '0',
  `em7_2` int unsigned NOT NULL default '0',
  `em7_3` int unsigned NOT NULL default '0',
  `em7_4` int unsigned NOT NULL default '0',
  `em7_5` int unsigned NOT NULL default '0',
  UNIQUE KEY `entry` (`entry`)
);
CREATE TABLE `objectloot` (
  `index` int unsigned NOT NULL auto_increment,
  `entryid` int unsigned NOT NULL default '0',
  `itemid` int unsigned NOT NULL default '0',
  `percentchance` float NOT NULL default '0',
  `heroicpercentchance` float NOT NULL default '0',
  `mincount` int unsigned NOT NULL default '1',
  `maxcount` int unsigned NOT NULL default '1',
  PRIMARY KEY  (`index`),
  UNIQUE KEY `index` (`index`),
  KEY `entryid` (`entryid`)
);
CREATE TABLE `petdefaultspells` (
  `entry` int NOT NULL default '0',
  `spell` int NOT NULL default '0'
);
CREATE TABLE `pickpocketingloot` (
  `index` int unsigned NOT NULL auto_increment,
  `entryid` int unsigned NOT NULL default '0',
  `itemid` int unsigned NOT NULL default '25',
  `percentchance` float NOT NULL default '100',
  `heroicpercentchance` float default '0',
  `mincount` int default '1',
  `maxcount` int default '1',
  PRIMARY KEY  (`index`),
  UNIQUE KEY `index` (`index`)
);
CREATE TABLE `playercreateinfo` (
  `Index` tinyint unsigned NOT NULL auto_increment,
  `race` tinyint unsigned NOT NULL default '0',
  `factiontemplate` int unsigned NOT NULL default '0',
  `class` tinyint unsigned NOT NULL default '0',
  `mapID` int unsigned NOT NULL default '0',
  `zoneID` int unsigned NOT NULL default '0',
  `positionX` float NOT NULL default '0',
  `positionY` float NOT NULL default '0',
  `positionZ` float NOT NULL default '0',
  `displayID` smallint unsigned NOT NULL default '0',
  `BaseStrength` tinyint unsigned NOT NULL default '0',
  `BaseAgility` tinyint unsigned NOT NULL default '0',
  `BaseStamina` tinyint unsigned NOT NULL default '0',
  `BaseIntellect` tinyint unsigned NOT NULL default '0',
  `BaseSpirit` tinyint unsigned NOT NULL default '0',
  `BaseHealth` int unsigned NOT NULL default '0',
  `BaseMana` int unsigned NOT NULL default '0',
  `BaseRage` int unsigned NOT NULL default '0',
  `BaseFocus` int unsigned NOT NULL default '0',
  `BaseEnergy` int unsigned NOT NULL default '0',
  `attackpower` int unsigned NOT NULL default '0',
  `mindmg` float NOT NULL default '0',
  `maxdmg` float NOT NULL default '0',
  PRIMARY KEY  (`Index`)
);
CREATE TABLE `playercreateinfo_bars` (
  `race` tinyint unsigned default NULL,
  `class` tinyint unsigned default NULL,
  `button` int unsigned default NULL,
  `action` int unsigned default NULL,
  `type` int unsigned default NULL,
  `misc` int unsigned default NULL
);
CREATE TABLE `playercreateinfo_items` (
  `indexid` tinyint unsigned NOT NULL default '0',
  `protoid` int unsigned NOT NULL default '0',
  `slotid` tinyint unsigned NOT NULL default '0',
  `amount` int unsigned NOT NULL default '0'
);
CREATE TABLE `playercreateinfo_skills` (
  `indexid` tinyint unsigned NOT NULL default '0',
  `skillid` int unsigned NOT NULL default '0',
  `level` int unsigned NOT NULL default '0',
  `maxlevel` int unsigned NOT NULL default '0'
);
CREATE TABLE `playercreateinfo_spells` (
  `indexid` tinyint unsigned NOT NULL default '0',
  `spellid` smallint unsigned NOT NULL default '0'
);
CREATE TABLE `prospectingloot` (
  `index` int unsigned NOT NULL auto_increment,
  `entryid` int unsigned NOT NULL default '0',
  `itemid` int unsigned NOT NULL default '25',
  `percentchance` float NOT NULL default '0',
  `heroicpercentchance` float NOT NULL default '0',
  `mincount` int unsigned NOT NULL default '1',
  `maxcount` int unsigned NOT NULL default '1',
  PRIMARY KEY  (`index`),
  UNIQUE KEY `index` (`index`)
);
CREATE TABLE `quests` (
  `entry` int unsigned NOT NULL default '0',
  `ZoneId` int unsigned NOT NULL default '0',
  `QuestSort` int unsigned NOT NULL default '0',
  `QuestFlags` int unsigned NOT NULL default '0',
  `MinLevel` int unsigned NOT NULL default '0',
  `MaxLevel` int unsigned NOT NULL default '0',
  `Type` int unsigned NOT NULL default '0',
  `RequiredRaces` int unsigned NOT NULL default '0',
  `RequiredClass` int unsigned NOT NULL default '0',
  `RequiredTradeskill` int unsigned NOT NULL default '0',
  `RequiredRepFaction` int unsigned NOT NULL default '0',
  `RequiredRepValue` int unsigned NOT NULL default '0',
  `LimitTime` int unsigned NOT NULL default '0',
  `SpecialFlags` int unsigned NOT NULL default '0',
  `PrevQuestId` int unsigned NOT NULL default '0',
  `NextQuestId` int unsigned NOT NULL default '0',
  `srcItem` int unsigned NOT NULL default '0',
  `SrcItemCount` int unsigned NOT NULL default '0',
  `Title` char(255) NOT NULL,
  `Details` text NOT NULL,
  `Objectives` text NOT NULL,
  `CompletionText` text NOT NULL,
  `IncompleteText` text NOT NULL,
  `EndText` text NOT NULL,
  `ObjectiveText1` text NOT NULL,
  `ObjectiveText2` text NOT NULL,
  `ObjectiveText3` text NOT NULL,
  `ObjectiveText4` text NOT NULL,
  `ReqItemId1` int unsigned NOT NULL default '0',
  `ReqItemId2` int unsigned NOT NULL default '0',
  `ReqItemId3` int unsigned NOT NULL default '0',
  `ReqItemId4` int unsigned NOT NULL default '0',
  `ReqItemCount1` int unsigned NOT NULL default '0',
  `ReqItemCount2` int unsigned NOT NULL default '0',
  `ReqItemCount3` int unsigned NOT NULL default '0',
  `ReqItemCount4` int unsigned NOT NULL default '0',
  `ReqKillMobOrGOId1` int unsigned NOT NULL default '0',
  `ReqKillMobOrGOId2` int unsigned NOT NULL default '0',
  `ReqKillMobOrGOId3` int unsigned NOT NULL default '0',
  `ReqKillMobOrGOId4` int unsigned NOT NULL default '0',
  `ReqKillMobOrGOCount1` int unsigned NOT NULL default '0',
  `ReqKillMobOrGOCount2` int unsigned NOT NULL default '0',
  `ReqKillMobOrGOCount3` int unsigned NOT NULL default '0',
  `ReqKillMobOrGOCount4` int unsigned NOT NULL default '0',
  `RewChoiceItemId1` int unsigned NOT NULL default '0',
  `RewChoiceItemId2` int unsigned NOT NULL default '0',
  `RewChoiceItemId3` int unsigned NOT NULL default '0',
  `RewChoiceItemId4` int unsigned NOT NULL default '0',
  `RewChoiceItemId5` int unsigned NOT NULL default '0',
  `RewChoiceItemId6` int unsigned NOT NULL default '0',
  `RewChoiceItemCount1` int unsigned NOT NULL default '0',
  `RewChoiceItemCount2` int unsigned NOT NULL default '0',
  `RewChoiceItemCount3` int unsigned NOT NULL default '0',
  `RewChoiceItemCount4` int unsigned NOT NULL default '0',
  `RewChoiceItemCount5` int unsigned NOT NULL default '0',
  `RewChoiceItemCount6` int unsigned NOT NULL default '0',
  `RewItemId1` int unsigned NOT NULL default '0',
  `RewItemId2` int unsigned NOT NULL default '0',
  `RewItemId3` int unsigned NOT NULL default '0',
  `RewItemId4` int unsigned NOT NULL default '0',
  `RewItemCount1` int unsigned NOT NULL default '0',
  `RewItemCount2` int unsigned NOT NULL default '0',
  `RewItemCount3` int unsigned NOT NULL default '0',
  `RewItemCount4` int unsigned NOT NULL default '0',
  `RewRepFaction1` int unsigned NOT NULL default '0',
  `RewRepFaction2` int unsigned NOT NULL default '0',
  `RewRepValue1` int NOT NULL default '0',
  `RewRepValue2` int NOT NULL default '0',
  `RewRepLimit` int unsigned NOT NULL default '0',
  `RewMoney` int unsigned NOT NULL default '0',
  `RewXP` int unsigned NOT NULL default '0',
  `RewSpell` int unsigned NOT NULL default '0',
  `CastSpell` int unsigned NOT NULL default '0',
  `PointMapId` int unsigned NOT NULL default '0',
  `PointX` float NOT NULL default '0',
  `PointY` float NOT NULL default '0',
  `PointOpt` int unsigned NOT NULL default '0',
  `RequiredMoney` int unsigned NOT NULL default '0',
  `ExploreTrigger1` int unsigned NOT NULL default '0',
  `ExploreTrigger2` int unsigned NOT NULL default '0',
  `ExploreTrigger3` int unsigned NOT NULL default '0',
  `ExploreTrigger4` int unsigned NOT NULL default '0',
  `RequiredQuest1` int unsigned NOT NULL default '0',
  `RequiredQuest2` int unsigned NOT NULL default '0',
  `RequiredQuest3` int unsigned NOT NULL default '0',
  `RequiredQuest4` int unsigned NOT NULL default '0',
  `ReceiveItemId1` int unsigned NOT NULL default '0',
  `ReceiveItemId2` int unsigned NOT NULL default '0',
  `ReceiveItemId3` int unsigned NOT NULL default '0',
  `ReceiveItemId4` int unsigned NOT NULL default '0',
  `ReceiveItemCount1` int unsigned NOT NULL default '0',
  `ReceiveItemCount2` int unsigned NOT NULL default '0',
  `ReceiveItemCount3` int unsigned NOT NULL default '0',
  `ReceiveItemCount4` int unsigned NOT NULL default '0',
  `IsRepeatable` int NOT NULL default '0',
  PRIMARY KEY  (`entry`),
  UNIQUE KEY `entry` (`entry`)
);
CREATE TABLE `recall` (
  `id` bigint unsigned NOT NULL auto_increment,
  `locname` varchar(100) NOT NULL,
  `map` int unsigned NOT NULL default '0',
  `positionX` float NOT NULL default '0',
  `positionY` float NOT NULL default '0',
  `positionZ` float NOT NULL default '0',
  PRIMARY KEY  (`id`)
);
CREATE TABLE `reputation_creature_onkill` (
  `creature_id` int NOT NULL,
  `faction_change_alliance` int NOT NULL,
  `faction_change_horde` int NOT NULL,
  `change_value` int NOT NULL,
  `rep_limit` int NOT NULL,
  KEY `index` (`creature_id`)
);
CREATE TABLE `reputation_faction_onkill` (
  `faction_id` int NOT NULL,
  `change_factionid_alliance` int NOT NULL,
  `change_deltamin_alliance` int NOT NULL,
  `change_deltamax_alliance` int NOT NULL,
  `change_factionid_horde` int NOT NULL,
  `change_deltamin_horde` int NOT NULL,
  `change_deltamax_horde` int NOT NULL,
  KEY `factindex` (`faction_id`)
);
CREATE TABLE `reputation_instance_onkill` (
  `mapid` int NOT NULL,
  `mob_rep_reward` int NOT NULL,
  `mob_rep_limit` int NOT NULL,
  `boss_rep_reward` int NOT NULL,
  `boss_rep_limit` int NOT NULL,
  `faction_change_alliance` int NOT NULL,
  `faction_change_horde` int NOT NULL
);
CREATE TABLE `skinningloot` (
  `index` int unsigned NOT NULL auto_increment,
  `entryid` int unsigned NOT NULL default '0',
  `itemid` int unsigned NOT NULL default '0',
  `percentchance` float NOT NULL default '0',
  `heroicpercentchance` float default '0',
  `mincount` int default '1',
  `maxcount` int default '1',
  PRIMARY KEY  (`index`),
  UNIQUE KEY `index` (`index`)
);
CREATE TABLE `spell_disable` (
  `spellid` int NOT NULL,
  `replacement_spellid` int NOT NULL
);
CREATE TABLE `spell_proc_data` (
  `name_hash` int NOT NULL,
  `proc_chance` int NOT NULL,
  `forced_proc_flags` int NOT NULL default '-1',
  PRIMARY KEY  (`name_hash`)
);
CREATE TABLE `spellextra` (
  `Id` int unsigned NOT NULL auto_increment,
  `specialtype` int unsigned default NULL,
  `enchantableslots` int unsigned default NULL,
  `ExtraFlags` int unsigned default NULL,
  PRIMARY KEY  (`Id`)
);
CREATE TABLE `spelloverride` (
  `overrideId` int unsigned NOT NULL default '0',
  `spellId` int unsigned NOT NULL default '0',
  UNIQUE KEY `overrideId` (`overrideId`,`spellId`)
);
CREATE TABLE `spells112` (
  `Id` int default '0',
  `School` int default '0',
  `Category` int default '0',
  `field4` int default '0',
  `DispelType` int default '0',
  `MechanicsType` int default '0',
  `Attributes` int default '0',
  `AttributesEx` int default '0',
  `Flags3` int default '0',
  `field10` int default '0',
  `field11` int default '0',
  `UNK12` int default '0',
  `UNK13` int default '0',
  `Targets` int default '0',
  `TargetCreatureType` int default '0',
  `RequiresSpellFocus` int default '0',
  `CasterAuraState` int default '0',
  `TargetAuraState` int default '0',
  `CastingTimeIndex` int default '0',
  `RecoveryTime` int default '0',
  `CategoryRecoveryTime` int default '0',
  `InterruptFlags` int default '0',
  `AuraInterruptFlags` int default '0',
  `ChannelInterruptFlags` int default '0',
  `procFlags` int default '0',
  `procChance` int default '0',
  `procCharges` int default '0',
  `maxLevel` int default '0',
  `baseLevel` int default '0',
  `spellLevel` int default '0',
  `DurationIndex` int default '0',
  `powerType` int default '0',
  `manaCost` int default '0',
  `manaCostPerlevel` int default '0',
  `manaPerSecond` int default '0',
  `manaPerSecondPerLevel` int default '0',
  `rangeIndex` int default '0',
  `speed` float default '0',
  `modalNextSpell` int default '0',
  `maxstack` int default '0',
  `Totem1` int default '0',
  `Totem2` int default '0',
  `Reagent1` int default '0',
  `Reagent2` int default '0',
  `Reagent3` int default '0',
  `Reagent4` int default '0',
  `Reagent5` int default '0',
  `Reagent6` int default '0',
  `Reagent7` int default '0',
  `Reagent8` int default '0',
  `ReagentCount1` int default '0',
  `ReagentCount2` int default '0',
  `ReagentCount3` int default '0',
  `ReagentCount4` int default '0',
  `ReagentCount5` int default '0',
  `ReagentCount6` int default '0',
  `ReagentCount7` int default '0',
  `ReagentCount8` int default '0',
  `EquippedItemClass` int default '0',
  `EquippedItemSubClass` int default '0',
  `RequiredItemFlags` int default '0',
  `Effect1` int default '0',
  `Effect2` int default '0',
  `Effect3` int default '0',
  `EffectDieSides1` int default '0',
  `EffectDieSides2` int default '0',
  `EffectDieSides3` int default '0',
  `EffectBaseDice1` int default '0',
  `EffectBaseDice2` int default '0',
  `EffectBaseDice3` int default '0',
  `EffectDicePerLevel1` float default '0',
  `EffectDicePerLevel2` float default '0',
  `EffectDicePerLevel3` float default '0',
  `EffectRealPointsPerLevel1` float default '0',
  `EffectRealPointsPerLevel2` float default '0',
  `EffectRealPointsPerLevel3` float default '0',
  `EffectBasePoints1` int default '0',
  `EffectBasePoints2` int default '0',
  `EffectBasePoints3` int default '0',
  `Effectunk1901` int default '0',
  `Effectunk1902` int default '0',
  `Effectunk1903` int default '0',
  `EffectImplicitTargetA1` int default '0',
  `EffectImplicitTargetA2` int default '0',
  `EffectImplicitTargetA3` int default '0',
  `EffectImplicitTargetB1` int default '0',
  `EffectImplicitTargetB2` int default '0',
  `EffectImplicitTargetB3` int default '0',
  `EffectRadiusIndex1` int default '0',
  `EffectRadiusIndex2` int default '0',
  `EffectRadiusIndex3` int default '0',
  `EffectApplyAuraName1` int default '0',
  `EffectApplyAuraName2` int default '0',
  `EffectApplyAuraName3` int default '0',
  `EffectAmplitude1` int default '0',
  `EffectAmplitude2` int default '0',
  `EffectAmplitude3` int default '0',
  `Effectunknown1` float default '0',
  `Effectunknown2` float default '0',
  `Effectunknown3` float default '0',
  `EffectChainTarget1` int default '0',
  `EffectChainTarget2` int default '0',
  `EffectChainTarget3` int default '0',
  `EffectSpellGroupRelation1` int default '0',
  `EffectSpellGroupRelation2` int default '0',
  `EffectSpellGroupRelation3` int default '0',
  `EffectMiscValue1` int default '0',
  `EffectMiscValue2` int default '0',
  `EffectMiscValue3` int default '0',
  `EffectTriggerSpell1` int default '0',
  `EffectTriggerSpell2` int default '0',
  `EffectTriggerSpell3` int default '0',
  `EffectPointsPerComboPoint1` float default '0',
  `EffectPointsPerComboPoint2` float default '0',
  `EffectPointsPerComboPoint3` float default '0',
  `SpellVisual` int default '0',
  `field114` int default '0',
  `dummy` int default '0',
  `CoSpell` int default '0',
  `spellPriority` int default '0',
  `Name` longtext,
  `NameAlt1` longtext,
  `NameAlt2` longtext,
  `NameAlt3` longtext,
  `NameAlt4` longtext,
  `NameAlt5` longtext,
  `NameAlt6` longtext,
  `NameAlt7` longtext,
  `NameFlags` longtext,
  `Rank` longtext,
  `RankAlt1` longtext,
  `RankAlt2` longtext,
  `RankAlt3` longtext,
  `RankAlt4` longtext,
  `RankAlt5` longtext,
  `RankAlt6` longtext,
  `RankAlt7` longtext,
  `RankFlags` longtext,
  `Description` longtext,
  `DescriptionAlt1` longtext,
  `DescriptionAlt2` longtext,
  `DescriptionAlt3` longtext,
  `DescriptionAlt4` longtext,
  `DescriptionAlt5` longtext,
  `DescriptionAlt6` longtext,
  `DescriptionAlt7` longtext,
  `DescriptionFlags` longtext,
  `BuffDescription` longtext,
  `BuffDescriptionAlt1` longtext,
  `BuffDescriptionAlt2` longtext,
  `BuffDescriptionAlt3` longtext,
  `BuffDescriptionAlt4` longtext,
  `BuffDescriptionAlt5` longtext,
  `BuffDescriptionAlt6` longtext,
  `BuffDescriptionAlt7` longtext,
  `buffdescflags` int default '0',
  `ManaCostPercentage` int default '0',
  `unkflags` int default '0',
  `StartRecoveryTime` int default '0',
  `StartRecoveryCategory` int default '0',
  `SpellFamilyName` int default '0',
  `SpellGroupType` int default '0',
  `unkne` int default '0',
  `MaxTargets` int default '0',
  `Spell_Dmg_Type` int default '0',
  `FG` int default '0',
  `FH` int default '0',
  `dmg_multiplier_1` float default '0',
  `dmg_multiplier_2` float default '0',
  `dmg_multiplier_3` float default '0',
  `FL` int default '0',
  `FM` int default '0',
  `FN` int default '0'
);
CREATE TABLE `teleport_coords` (
  `id` int unsigned NOT NULL default '0',
  `name` char(255) NOT NULL,
  `mapId` int unsigned NOT NULL default '0',
  `x` float NOT NULL default '0',
  `y` float NOT NULL default '0',
  `z` float NOT NULL default '0',
  `totrigger` int unsigned NOT NULL default '0',
  PRIMARY KEY  (`id`)
);
CREATE TABLE `totemspells` (
  `spellId` int unsigned NOT NULL default '0',
  `spellToCast1` int unsigned NOT NULL default '0',
  `spellToCast2` int unsigned NOT NULL default '0',
  `spellToCast3` int unsigned NOT NULL default '0',
  PRIMARY KEY  (`spellId`)
);
CREATE TABLE `trainer_defs` (
  `entry` int unsigned NOT NULL default '0',
  `required_skill` int unsigned NOT NULL default '0',
  `required_skillvalue` int unsigned default '0',
  `req_class` int unsigned NOT NULL default '0',
  `trainer_type` int unsigned NOT NULL default '0',
  `trainer_ui_window_message` text character set utf8,
  `can_train_gossip_textid` int NOT NULL,
  `cannot_train_gossip_textid` int NOT NULL,
  PRIMARY KEY  (`entry`),
  UNIQUE KEY `entry` (`entry`),
  KEY `entry_2` (`entry`)
);
CREATE TABLE `trainer_spells` (
  `entry` int unsigned NOT NULL default '0',
  `cast_spell` int unsigned NOT NULL default '0',
  `spellcost` int unsigned NOT NULL default '0',
  `reqspell` int unsigned NOT NULL default '0',
  `reqskill` int unsigned NOT NULL default '0',
  `reqskillvalue` int unsigned NOT NULL default '0',
  `reqlevel` int unsigned NOT NULL default '0',
  `deletespell` int unsigned NOT NULL default '0',
  `is_prof` tinyint unsigned NOT NULL default '0',
  PRIMARY KEY  (`entry`,`cast_spell`),
  KEY `entry` (`entry`)
);
CREATE TABLE `transport_data` (
  `entry` int unsigned NOT NULL default '0',
  `name` text,
  `period` int unsigned NOT NULL default '0',
  PRIMARY KEY  (`entry`)
);
CREATE TABLE `vendors` (
  `vendorGuid` int unsigned NOT NULL default '0',
  `itemGuid` int unsigned NOT NULL default '0',
  `amount` int NOT NULL default '0'
);
CREATE TABLE `weather` (
  `zoneId` int unsigned NOT NULL default '0',
  `high_chance` int unsigned NOT NULL default '0',
  `high_type` int unsigned NOT NULL default '0',
  `med_chance` int unsigned NOT NULL default '0',
  `med_type` int unsigned NOT NULL default '0',
  `low_chance` int unsigned NOT NULL default '0',
  `low_type` int unsigned NOT NULL default '0',
  PRIMARY KEY  (`zoneId`)
);
CREATE TABLE `worldmap_info` (
  `entry` int unsigned NOT NULL default '0',
  `screenid` int unsigned default '0',
  `type` int unsigned default '0',
  `maxplayers` int unsigned default '0',
  `minlevel` int unsigned default '1',
  `repopx` float default '0',
  `repopy` float default '0',
  `repopz` float default '0',
  `repopentry` int unsigned default '0',
  `area_name` varchar(100) default '0',
  `flags` int unsigned NOT NULL default '0',
  `cooldown` int unsigned NOT NULL default '0',
  `lvl_mod_a` int unsigned NOT NULL default '0',
  `required_quest` int unsigned NOT NULL default '0',
  `required_item` int unsigned NOT NULL default '0',
  PRIMARY KEY  (`entry`)
);
CREATE TABLE `zoneguards` (
  `zoneId` int unsigned NOT NULL,
  `hordeEntry` int unsigned default NULL,
  `allianceEntry` int unsigned default NULL
);
